#spring:
#  cloud:
#    stream:
#      kafka:
#        binder:
#          auto-add-partitions: true
#
#      bindings:
#        checkBookEventProcessor-in-0:
#          destination: create-book
#        checkBookEventProcessor-out-0:
#          destination: store-book
#server:
#  port: 8093

server:
  port: 8051

spring:
  application:
    name: check-book-service
  profiles:
    active: dev
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
      retry:
        max-attempts: 20
        max-interval: 15000
        initial-interval: 10000
      discovery:
        enabled: true
        service-id: config-server
    bus:
      refresh:
        enabled: true
      env:
        enabled: true
  kafka:
    bootstrap-servers: http://localhost:9092

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

