spring:
  application:
    name: eureka-client
server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    eureka-service-url-poll-interval-seconds: 35
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30