spring:
  zipkin:
    enabled: true
    base-url: http://62.84.122.194:9411/
  data:
    mongodb:
      host: 62.84.122.194
      port: 27017
      database: moviedb
  cloud:
    config:
        enabled: false
  application:
    name: book-service
server:
  port: 8074

Lospring:
  sleuth:
    sampler:
      probability: 2.0

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    eureka-service-url-poll-interval-seconds: 35
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30