server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_ADDR:http://localhost:9092}
    bus:
      enabled: true
      id: config-server

    config:
      server:
        git:
          uri: https://github.com/korochev/srping-cloud-course
          searchPaths: "ms-config-properties/{application}/{profile}"
          clone-on-start: true
          default-label: master

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}